### ISSUE TITLE
日记好像没法备份？

### ISSUE THREAD

**Issue by guozhangwang** [doufen-org/tofu#1]
备份完成后，日记栏显示依然为空...

**Comment by tabris17** [comment]
只有日记有问题吗？应该是脚本出错了，可能是数据格式有问题。
![image](https://user-images.githubusercontent.com/3053179/62419885-cfec7d80-b6bc-11e9-8a24-dbabf5e3bad0.png)
打开background.html页面，按F12查看Console打印出来的错误信息。
![image](https://user-images.githubusercontent.com/3053179/62419891-ed214c00-b6bc-11e9-8add-7c8739adc2e5.png)
劳烦把错误信息贴出来

**Comment by tabris17** [comment]
或者能豆邮我你的豆瓣ID吗？我直接调试看看

**Comment by guozhangwang** [comment]
我重新开启了一次任务之后好像就好了，多谢！这个工具非常有用！值得推广。

**Comment by tabris17** [comment]
那可能是当时的网络问题导致的备份中断
