### ISSUE TITLE
无法备份书影音

### ISSUE THREAD

**Issue by yuesidu** [doufen-org/tofu#12]
![截屏2019-12-09下午4 30 20](https://user-images.githubusercontent.com/51895657/70419869-5832c300-1aa1-11ea-8099-a1cc19547a16.png)

如图，点击“开始”按钮之后，并不会开始，状态一直卡在“已停止”，请问是什么原因呢？

谢谢。

**Comment by yuesidu** [comment]
![截屏2019-12-09下午4 45 43](https://user-images.githubusercontent.com/51895657/70420765-5f5ad080-1aa3-11ea-8e2f-f443d1bc197c.png)

附上服务日志截图

**Comment by yuesidu** [comment]
啊已经解决了，可能是因为在境外，用VPN翻回去就可以正常备份了。大感谢！

**Comment by tabris17** [comment]
今天下午我也打不开m.douban.com
