### ISSUE TITLE
可有加入导出图片功能的计划？

### ISSUE THREAD

**Issue by jdxyw** [doufen-org/tofu#2]

**Comment by einverne** [comment]
这里可以导出相册 https://github.com/einverne/douban-dl 有点久了，不知道还能不能用

**Comment by tabris17** [comment]
由于Chrome扩展没有写入本地文件的权限，所以无法下载图片。倒是可以把相册的图片链接导出，然后导入下载工具进行下载，不过没有归档整理，意义不大。

图片备份会在以后的“里豆瓣”项目中实现

**Comment by tabris17** [comment]
新版本可以将图片导出（上传）到Cloudinary云存储中
