### ISSUE TITLE
增加：搜索功能

### ISSUE THREAD

**Issue by bekindtoyourself** [doufen-org/tofu#23]
你好！

谢谢开发者发源出这好的工具。

不知以后有无增加搜索功能？
或是在设置页面可以设置 page_size，然后可以全部显示，然后自己用 Chrome 自带的搜索功能？

谢谢！

**Comment by tabris17** [comment]
因为此工具使用的IndexedDB并不支持全文检索，所以建议导出为Excel表格后进行搜索

设置pagesize似乎并不是一个好方案

**Comment by bekindtoyourself** [comment]
”导出为Excel表格后进行搜索“也挺好的。
