### ISSUE TITLE
无法导出广播

### ISSUE THREAD

**Issue by hellomonkeybutt** [doufen-org/tofu#38]
广播都备份好了,但是导出广播的时候会一直转圈圈. 其他项目导出没有问题. 我没有笔记. 谢谢!

**Comment by hellomonkeybutt** [comment]
豆瓣最新的APP测试版增加了禁止非好友浏览30天以前的功能，不知道会不会影响豆伴的备份……我只想保留一份自己的广播做记录，拜托了，谢谢。

**Comment by tabris17** [comment]
方便告知你的豆瓣ID吗？我抓取你的数据导出试试看。一般是由异常数据导致脚本出错造成的

**Comment by hellomonkeybutt** [comment]
你好，请问下图中的这个就是豆瓣ID对吗？谢谢。
[image: image.png]

**Comment by tabris17** [comment]
我看不到图片……
你把豆瓣个人主页地址发给我就可以了

**Comment by hellomonkeybutt** [comment]
你好：
我的主页地址是https://www.douban.com/people/kissthebunny/
谢谢

**Comment by tabris17** [comment]
是「广播仅个人可见」导致的，已经修复了。升级到0.8.4再试试看

**Comment by hellomonkeybutt** [comment]
果然可以了！谢谢！
