### ISSUE TITLE
备份 cloudinary 报错

### ISSUE THREAD

**Issue by sunyunxian** [doufen-org/tofu#39]
相关配置是按照教程设置的，但是会报错

命令行报错信息
```bash
[2021-01-23T07:29:01.998Z] DEBUG: Fetching https://api.cloudinary.com/v1_1/franksun/image/upload...

[2021-01-23T07:29:03.096Z] ERROR: Fail to run task:Error: Cloudinary 接口返回错误

[2021-01-23T07:29:03.097Z] DEBUG: Close local database

```

接口报错信息
```json
{
"error": {
"message": "Upload preset must be specified when using unsigned upload"
}
}
{
error: {
message: "Upload preset must be specified when using unsigned upload"
}
}
```

**Comment by tabris17** [comment]
看提示应该是第二步设置有问题

**Comment by sunyunxian** [comment]
> 看提示应该是第二步设置有问题

额，我又按照教程设置了一边。[这是设置网址](https://blog.doufen.org/posts/how-to-upload-images-to-cloudinary/)，保证一模一样，一直是报错的。但是神奇的是，居然有一次备份成功，这就很玄幻了，具体我也不清楚。

感谢你的回复。Thanks!

**Comment by tabris17** [comment]
奇怪，等我有空了试试看

Frank Sun <notifications@github.com>于2021年1月25日 周一10:31写道：

**Comment by tabris17** [comment]
你看一下，Signing Mode 是否设置成 unsigned

![image](https://user-images.githubusercontent.com/3053179/105795927-a61dc980-5fc8-11eb-9e99-a06b1f6722d9.png)

**Comment by sunyunxian** [comment]
> 你看一下，Signing Mode 是否设置成 unsigned
> 
> ![image](https://user-images.githubusercontent.com/3053179/105795927-a61dc980-5fc8-11eb-9e99-a06b1f6722d9.png)

![image](https://user-images.githubusercontent.com/42464504/105803784-1df3f000-5fd9-11eb-962f-23b70d74ffee.png)

设置应该是对的。

**Comment by tabris17** [comment]
> > 你看一下，Signing Mode 是否设置成 unsigned
> > ![image](https://user-images.githubusercontent.com/3053179/105795927-a61dc980-5fc8-11eb-9e99-a06b1f6722d9.png)
> 
> ![image](https://user-images.githubusercontent.com/42464504/105803784-1df3f000-5fd9-11eb-962f-23b70d74ffee.png)
> 
> 设置应该是对的。

好像没问题，不过我没有设置Folder，留空了
