### ISSUE TITLE
无法完成书影音游备份

### ISSUE THREAD

**Issue by shouxishao** [doufen-org/tofu#46]
<img width="852" alt="Screen Shot 2021-07-24 at 10 43 49 PM" src="https://user-images.githubusercontent.com/87920724/126885982-be16557b-b4f3-48f1-833c-3e230c8682c9.png">
进度条走20%左右直接变成进度条消失，上面说”等待任务“。反复刷新后不能解决。

**Comment by tabris17** [comment]
方便私下提供你的豆瓣账号吗？我要抓取试试看。应该是特殊数据造成的错误

**Comment by shouxishao** [comment]
谢谢回复，用这个试试看？https://www.douban.com/people/kayst510/

**Comment by shouxishao** [comment]
> 方便私下提供你的豆瓣账号吗？我要抓取试试看。应该是特殊数据造成的错误

谢谢回复！可以给一个邮箱吗？我把账号网址发给你

**Comment by tabris17** [comment]
> > 方便私下提供你的豆瓣账号吗？我要抓取试试看。应该是特殊数据造成的错误
> 
> 谢谢回复！可以给一个邮箱吗？我把账号网址发给你

admin@doufen.org

**Comment by tabris17** [comment]
某条游戏记录引起的，有人反应了相同的问题。我已经修复了，等我发包。

应该是这条引起的：https://www.douban.com/game/10733564/

**Comment by shouxishao** [comment]
> 某条游戏记录引起的，有人反应了相同的问题。我已经修复了，等我发包。
> 
> 应该是这条引起的：https://www.douban.com/game/10733564/

大谢！今天备份成功了！
