### ISSUE TITLE
豆列里收藏的部分不能备份是吗

### ISSUE THREAD

**Issue by it-rains** [doufen-org/tofu#64]
如题。想备份我收藏的豆列。

**Comment by AntaresShao** [comment]
同问，不知道为啥**关注的_别人_的豆列**不能备份。关注的豆列一栏是空的。

**Comment by daisyfan128** [comment]
同问，想备份我收藏的豆列有没有什么好方法

**Comment by AntaresShao** [comment]
@it-rains  请问姐妹是已经解决这个问题了吗？看到你关闭了issue。
@daisyfan128 刚刚看issue里 #31 和 #16 也是说相关问题的，按照开发者2020年回复所说的就是：
>这个已经确认，是豆瓣把接口给封掉了，暂时没办法

不知道现在还能不能解决了。
