### ISSUE TITLE
能否支持 webdav 备份功能

### ISSUE THREAD

**Issue by ChellyL** [doufen-org/tofu#69]
如题，[Cloudinary](https://cloudinary.com/) 的备份我总是失败

**Comment by Charliecheung2** [comment]
cloudinary失败的原因有没有？如果有并且可以解决的，感觉修复这个错误比新增一个功能要好。

**Comment by ChellyL** [comment]
> cloudinary失败的原因有没有？如果有并且可以解决的，感觉修复这个错误比新增一个功能要好。

刚才去cloudinary看了下，之前的突然有之前的备份了，看来豆坟的备份有延时性，我以为是失败了……
