### ISSUE TITLE
导出的xlst 希望添加imdb的id

### ISSUE THREAD

**Issue by murdercdh** [doufen-org/tofu#79]
现在的头文件是这样的，

标题 | 简介 | 豆瓣评分 | 链接 | 创建时间 | 我的评分 | 标签 | 评论
-- | -- | -- | -- | -- | -- | -- | --
光灵 | 2017 / 美国 / 动作 犯罪 奇幻 / 大卫·阿耶 / 威尔·史密斯 乔尔·埃哲顿 | 6.4 | https://movie.douban.com/subject/26739551/ | 2022-08-22 18:55:53 |   |   |  

希望加一列imdb的id， 这样我才能方便导入到自己的imdb账号里面

**Comment by tabris17** [comment]
因为用于抓取数据的豆瓣接口没有提供IMDB信息，所以暂时没法添加IMDB字段
